
[snowflake]
user = "MARICON03"
password = "Snowhite&7dwarfx"
account = "RZHQQEA-UHB53236" # e.g., xy12345.west-europe.azure
warehouse = "COMPUTE_WH"
database = "smoothies"
schema = "public"
role = "SYSADMIN"
